export const types = {
    SET_PLAYSTATION_AUTHENTICATED: 'SET_PLAYSTATION_AUTHENTICATED',
    PS_USER: 'PS_USER',
    PS_EMAIL: 'PS_EMAIL',
    PS_PASSWORD: 'PS_PASSWORD',
    PS_FRIENDS: 'PS_FRIENDS',
    PS_GAMES: 'PS_GAMES',

    SET_XBOX_AUTHENTICATED: 'SET_XBOX_AUTHENTICATED',
    XBOX_USER: 'XBOX_USER',
    XBOX_EMAIL: 'XBOX_EMAIL',
    XBOX_PASSWORD: 'XBOX_PASSWORD',
    XBOX_FRIENDS: 'XBOX_FRIENDS',
    XBOX_GAMES: 'XBOX_GAMES'

}